name: shrink_workspace
packages:
  - shrink_core
  - shrink_flutter

scripts:
  analyze:
    run: dart analyze .
    description: Analyze all packages

  format:
    run: dart format .
    description: Format all packages

  test:
    run: |
      melos exec --scope="shrink" -- dart test
      melos exec --scope="shrink_flutter" -- flutter test
    description: Run tests in shrink_core (Dart) and shrink_flutter (Flutter)

  sync_readme:
    run: dart ./scripts/sync_readme.dart
    description: Sync README from shrink_core to shrink_flutter
