name: shrink
description: "Efficient data compression made easy. Reduces data footprint by 5-20x, optimized for Firebase, JSON, and structured data"
version: 1.4.2
repository: https://github.com/jozzzzep/shrink
issue_tracker: https://github.com/jozzzzep/shrink/issues
homepage: https://github.com/jozzzzep/shrink
documentation: https://github.com/jozzzzep/shrink/blob/main/README.md

topics:
  - compress
  - bytes
  - serialization
  - firebase
  - easy

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  more: ^4.5.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

# This section identifies the platforms the package supports
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
