name: shrink_flutter
description: Flutter utilities for the `shrink` package, including async compression and future Flutter-specific tools. For core features, use `shrink`.
version: 0.0.4
homepage: https://github.com/jozzzzep/shrink
repository: https://github.com/jozzzzep/shrink/tree/main/shrink_flutter
issue_tracker: https://github.com/jozzzzep/shrink/issues
topics:
  - compress
  - compression
  - simple
  - firebase
  - easy

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shrink: ^1.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
